### PR TITLE
Fix the indentation in the `case` statement, the appending to pacman.conf if reran, general patches

### PR DESCRIPTION
**Pull request by youmukonpaku1337**

### CODE REVIEW

**Comment by RaptaG** [comment]
Why did you turn `Chaotic-AUR` to `chaotic AUR` lol

**Comment by me0wing-katt0** [comment]
pls merge

**Comment by youmukonpaku1337** [comment]
> Why did you turn `Chaotic-AUR` to `chaotic AUR` lol

because yes

**Comment by youmukonpaku1337** [comment]
i am now angery after you changed it

**Comment by RaptaG** [comment]
> i am now angery after you changed it

Whyy it looks better:)

**Comment by youmukonpaku1337** [comment]
idk

**Comment by youmukonpaku1337** [comment]
merge though

**Comment by youmukonpaku1337** [comment]
pog

**Pull request merged**
